[package]
name = "aztec_big_gist"
type = "contract"
authors = ["drgorillamd"]
compiler_version = ">=0.23.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.23.0", directory="yarn-project/aztec-nr/aztec" }