
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  AztecAddress,
  AztecAddressLike,
  CompleteAddress,
  Contract,
  ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  ContractMethod,
  DeployMethod,
  EthAddress,
  EthAddressLike,
  FieldLike,
  Fr,
  PXE,
  Point,
  PublicKey,
  Wallet,
} from '@aztec/aztec.js';
import MyNoteTestContractArtifactJson from '../target/MyNoteTest.json' assert { type: 'json' };
export const MyNoteTestContractArtifact = MyNoteTestContractArtifactJson as ContractArtifact;

/**
 * Type-safe interface for contract MyNoteTest;
 */
export class MyNoteTestContract extends ContractBase {
  
  private constructor(
    completeAddress: CompleteAddress,
    wallet: Wallet,
    portalContract = EthAddress.ZERO
  ) {
    super(completeAddress, MyNoteTestContractArtifact, wallet, portalContract);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, MyNoteTestContract.artifact, wallet) as Promise<MyNoteTestContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(pxe: PXE, _new_value: AztecAddressLike) {
    return new DeployMethod<MyNoteTestContract>(Point.ZERO, pxe, MyNoteTestContractArtifact, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public key to derive the address.
   */
  public static deployWithPublicKey(pxe: PXE, publicKey: PublicKey, _new_value: AztecAddressLike) {
    return new DeployMethod<MyNoteTestContract>(publicKey, pxe, MyNoteTestContractArtifact, Array.from(arguments).slice(2));
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return MyNoteTestContractArtifact;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public methods!: {
    
    /** test_uses_my_note() */
    test_uses_my_note: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };
}
